// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: models/v1/delete_account_confirmation.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteAccountConfirmation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Salt          string                 `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountConfirmation) Reset() {
	*x = DeleteAccountConfirmation{}
	mi := &file_models_v1_delete_account_confirmation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountConfirmation) ProtoMessage() {}

func (x *DeleteAccountConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_delete_account_confirmation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountConfirmation.ProtoReflect.Descriptor instead.
func (*DeleteAccountConfirmation) Descriptor() ([]byte, []int) {
	return file_models_v1_delete_account_confirmation_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteAccountConfirmation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DeleteAccountConfirmation) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *DeleteAccountConfirmation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_models_v1_delete_account_confirmation_proto protoreflect.FileDescriptor

const file_models_v1_delete_account_confirmation_proto_rawDesc = "" +
	"\n" +
	"+models/v1/delete_account_confirmation.proto\x12\tmodels.v1\"Y\n" +
	"\x19DeleteAccountConfirmation\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\tR\x04salt\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04nameb\x06proto3"

var (
	file_models_v1_delete_account_confirmation_proto_rawDescOnce sync.Once
	file_models_v1_delete_account_confirmation_proto_rawDescData []byte
)

func file_models_v1_delete_account_confirmation_proto_rawDescGZIP() []byte {
	file_models_v1_delete_account_confirmation_proto_rawDescOnce.Do(func() {
		file_models_v1_delete_account_confirmation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_v1_delete_account_confirmation_proto_rawDesc), len(file_models_v1_delete_account_confirmation_proto_rawDesc)))
	})
	return file_models_v1_delete_account_confirmation_proto_rawDescData
}

var file_models_v1_delete_account_confirmation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_v1_delete_account_confirmation_proto_goTypes = []any{
	(*DeleteAccountConfirmation)(nil), // 0: models.v1.DeleteAccountConfirmation
}
var file_models_v1_delete_account_confirmation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_v1_delete_account_confirmation_proto_init() }
func file_models_v1_delete_account_confirmation_proto_init() {
	if File_models_v1_delete_account_confirmation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_v1_delete_account_confirmation_proto_rawDesc), len(file_models_v1_delete_account_confirmation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_v1_delete_account_confirmation_proto_goTypes,
		DependencyIndexes: file_models_v1_delete_account_confirmation_proto_depIdxs,
		MessageInfos:      file_models_v1_delete_account_confirmation_proto_msgTypes,
	}.Build()
	File_models_v1_delete_account_confirmation_proto = out.File
	file_models_v1_delete_account_confirmation_proto_goTypes = nil
	file_models_v1_delete_account_confirmation_proto_depIdxs = nil
}
