services:
  api:
    container_name: ubrato-storage-api
    image: ubrato-storage-api
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ubrato-storage-files:${STORAGE_FOLDER}
    env_file:
      - .env

volumes:
  ubrato-storage-files:
    name: ubrato-storage-files
