# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/v1/delete_account_confirmation.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n+models/v1/delete_account_confirmation.proto\x12\tmodels.v1"F\n\x19\x44\x65leteAccountConfirmation\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04salt\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\tb\x06proto3'
)


_DELETEACCOUNTCONFIRMATION = DESCRIPTOR.message_types_by_name["DeleteAccountConfirmation"]
DeleteAccountConfirmation = _reflection.GeneratedProtocolMessageType(
    "DeleteAccountConfirmation",
    (_message.Message,),
    {
        "DESCRIPTOR": _DELETEACCOUNTCONFIRMATION,
        "__module__": "models.v1.delete_account_confirmation_pb2",
        # @@protoc_insertion_point(class_scope:models.v1.DeleteAccountConfirmation)
    },
)
_sym_db.RegisterMessage(DeleteAccountConfirmation)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _DELETEACCOUNTCONFIRMATION._serialized_start = 58
    _DELETEACCOUNTCONFIRMATION._serialized_end = 128
# @@protoc_insertion_point(module_scope)
