"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DeleteAccountConfirmation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    SALT_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    email: builtins.str
    salt: builtins.str
    name: builtins.str
    def __init__(
        self,
        *,
        email: builtins.str = ...,
        salt: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email", "name", b"name", "salt", b"salt"]) -> None: ...

global___DeleteAccountConfirmation = DeleteAccountConfirmation
