CREATE SCHEMA IF NOT EXISTS admin;

CREATE TABLE admin.users(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login        TEXT NOT NULL UNIQUE,
    password     TEXT NOT NULL
);

CREATE TABLE admin.sessions(
    id                          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                     INT REFERENCES admin.users(id) ON DELETE CASCADE,
    ip_address                  TEXT,
    refresh_token               UUID NOT NULL,
    created_at                  BIGINT,
    refresh_token_expired_at    BIGINT NOT NULL
);

INSERT INTO admin.users
    (login, password)
VALUES
    ('admin', '$2a$10$KZEwm6oKKtZFQExFQom/QOBUff9lzLL0znZEIlrRzzNjHQDkPOA3m');
