http:
  address: "0.0.0.0"
  port: 3000
  timeout: 5s
repo:
  host: "localhost"
  port: 5432
  database: "postgres"
  user: "postgres"
  password: 12345
  auto_migrate: false
jwt:
  secret: "secret"
  lifetime:
    access: 30m
    refresh: 24h
swaggerui:
  swagger_ui_path: ./swaggerui
debug: false